### ISSUE TITLE
Repo does not build

### ISSUE THREAD

**Issue by agarmu** [TheCoderMerlin/Scenes3D#3]
The repo does not build, and has some compilation errors at be2d0d5c5804ca4ff2d03c187a9cac1922b70f89
<img width="1011" alt="Screen Shot 2021-03-30 at 12 00 08 PM" src="https://user-images.githubusercontent.com/55563106/113027244-7a959780-914f-11eb-8a5f-5c2d6f237573.png">

**Comment by william-paroff** [comment]
The first error has been resolved.
The code that resulted in the bottom errors is being redone from scratch.
